add_newline = false

[character]
symbol = "⟶"                    
use_symbol_for_status = true   

[cmd_duration]
min_time = 500
prefix = "⌛ "

[battery]
full_symbol = "🔌"        
charging_symbol = "⚡"     
discharging_symbol = "🔋"   

[[battery.display]]
threshold = 30               
style = "bold yellow"         

[[battery.display]]
threshold = 10                 
style = "bold red"              

# [git_branch]
# symbol = "🌱 "
# truncation_length = 10
# truncation_symbol = ""

[git_commit]
commit_hash_length = 4

[git_state]
progress_divider = " of "
cherry_pick = "🍒 PICKING"

[git_status]
conflicted = "🏳"
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
untracked = "🤷‍"
stashed = "📦"
modified = "📝"
staged.value = "++"
staged.style = "green"
staged_count.enabled = true
staged_count.style = "green"
renamed = "👅"
deleted = "🗑"

[memory_usage]
disabled = false
show_percentage = true
show_swap = true
threshold = 30
style = "bold dimmed green"

[hostname]    
ssh_only = false
prefix = "❮ "
suffix = "❯"
style = "bold dimmed white"
disabled = true

[aws]
symbol = "☁️ "

[conda]
symbol = " "

[docker]
symbol = " 🐳 "

[elixir]
symbol = " "

[elm]
symbol = " 🌳 "

[git_branch]
symbol = "🌱 "

[golang]
symbol = " 🐹 "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " ⬢ "

[package]
symbol = "📦 "

[php]
symbol = "🐘 "

[python]
symbol = "🐍 "

[ruby]
symbol = " 💎 "

[rust]
symbol = " 𝗥 "

